title: 梁耀荣
description: 华中师范大学统计系本科生

url: http://liangyorong.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html


social:
#   github: liangyaorong


google_analytics: "UA-58263416-1"
