# build
markdown: kramdown
permalink: /blog/:year/:title/
exclude:
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts: ./_noita
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
noita:
  name: 梁耀荣
  description: 华中师范大学统计学本科生一枚
  author:
    name: Anatol Broder
    url: http://penibelst.de/
  lang: en
  favicons:
    - /assets/2014/04/21/favicon-152.png
  topbar:
    toggle: Menu
    right:
      - name: GitHub
        url: https://github.com/liangyaorong
      - name: Blog
        url: /blog/

